// Theme configuration - Centralized theme definitions
export const themes = {
    golden: {
        name: 'Golden',
        description: 'Classic luxury gold on dark',
        isDark: true,
        lightMode: false,
        colors: {
            '--color-bg-base': '#000000',
            '--color-bg-card': '#0a0a0a',
            '--color-bg-elevated': '#141414',
            '--color-text-main': '#ffffff',
            '--color-text-muted': '#888888',
            '--color-border': '#222222',
            '--color-border-hover': '#ffffff',
            '--color-gold': '#d4af37',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#b8860b',
            '--color-gold-bg': 'rgba(212, 175, 55, 0.15)',
            '--color-card-gradient-from': '#0a0a0a',
            '--color-card-gradient-to': '#050505',
            '--color-card-gradient-ai-from': '#0a0a0a',
            '--color-card-gradient-ai-to': '#040404',
        },
        lightColors: {
            '--color-bg-base': '#ffffff',
            '--color-bg-card': '#fafafa',
            '--color-bg-elevated': '#f0f0f0',
            '--color-text-main': '#000000',
            '--color-text-muted': '#888888',
            '--color-border': '#e5e5e5',
            '--color-border-hover': '#000000',
            '--color-gold': '#d4af37',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#b8860b',
            '--color-gold-bg': 'rgba(212, 175, 55, 0.1)',
            '--color-card-gradient-from': '#fafafa',
            '--color-card-gradient-to': '#f5f5f5',
            '--color-card-gradient-ai-from': '#fafafa',
            '--color-card-gradient-ai-to': '#f0f0f0',
        },
    },
    goblin: {
        name: 'Goblin',
        description: 'Premium goblin aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#050a05',
            '--color-bg-card': '#051408',
            '--color-bg-elevated': '#051e0a',
            '--color-text-main': '#f2fff6',
            '--color-text-muted': '#a6ffbe',
            '--color-border': '#042f0e',
            '--color-border-hover': '#00ff44',
            '--color-gold': '#00ff44',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#00b330',
            '--color-gold-bg': 'rgba(0, 255, 68, 0.12)',
            '--color-card-gradient-from': '#051408',
            '--color-card-gradient-to': '#050a05',
            '--color-card-gradient-ai-from': '#051408',
            '--color-card-gradient-ai-to': '#040804',
        },
        lightColors: {
            '--color-bg-base': '#f2fff2',
            '--color-bg-card': '#edfaed',
            '--color-bg-elevated': '#e6f2e6',
            '--color-text-main': '#001907',
            '--color-text-muted': '#005918',
            '--color-border': '#dae6da',
            '--color-border-hover': '#00ff44',
            '--color-gold': '#00ff44',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#00cc36',
            '--color-gold-bg': 'rgba(0, 255, 68, 0.12)',
            '--color-card-gradient-from': '#edfaed',
            '--color-card-gradient-to': '#f2fff2',
            '--color-card-gradient-ai-from': '#edfaed',
            '--color-card-gradient-ai-to': '#f5fff5',
        },
    },
    crimson: {
        name: 'Crimson',
        description: 'Premium crimson aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#100507',
            '--color-bg-card': '#180609',
            '--color-bg-elevated': '#20060b',
            '--color-text-main': '#fdf3f5',
            '--color-text-muted': '#f3adbb',
            '--color-border': '#2f070f',
            '--color-border-hover': '#dc143c',
            '--color-gold': '#DC143C',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#9a0e2a',
            '--color-gold-bg': 'rgba(220, 20, 60, 0.12)',
            '--color-card-gradient-from': '#180609',
            '--color-card-gradient-to': '#100507',
            '--color-card-gradient-ai-from': '#180609',
            '--color-card-gradient-ai-to': '#0d0406',
        },
        lightColors: {
            '--color-bg-base': '#fff2f4',
            '--color-bg-card': '#faedef',
            '--color-bg-elevated': '#f2e6e8',
            '--color-text-main': '#160206',
            '--color-text-muted': '#4d0715',
            '--color-border': '#e6dadc',
            '--color-border-hover': '#dc143c',
            '--color-gold': '#DC143C',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#b01030',
            '--color-gold-bg': 'rgba(220, 20, 60, 0.12)',
            '--color-card-gradient-from': '#faedef',
            '--color-card-gradient-to': '#fff2f4',
            '--color-card-gradient-ai-from': '#faedef',
            '--color-card-gradient-ai-to': '#fff5f6',
        },
    },
    midnight: {
        name: 'Midnight',
        description: 'Premium midnight aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#020617',
            '--color-bg-card': '#040b20',
            '--color-bg-elevated': '#071029',
            '--color-text-main': '#f5f9ff',
            '--color-text-muted': '#bad3fc',
            '--color-border': '#0b1938',
            '--color-border-hover': '#3b82f6',
            '--color-gold': '#3b82f6',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#295bac',
            '--color-gold-bg': 'rgba(59, 130, 246, 0.12)',
            '--color-card-gradient-from': '#040b20',
            '--color-card-gradient-to': '#020617',
            '--color-card-gradient-ai-from': '#040b20',
            '--color-card-gradient-ai-to': '#020512',
        },
        lightColors: {
            '--color-bg-base': '#f8fafc',
            '--color-bg-card': '#f3f5f7',
            '--color-bg-elevated': '#eceeef',
            '--color-text-main': '#060d19',
            '--color-text-muted': '#152e56',
            '--color-border': '#dfe1e3',
            '--color-border-hover': '#3b82f6',
            '--color-gold': '#3b82f6',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#2f68c5',
            '--color-gold-bg': 'rgba(59, 130, 246, 0.12)',
            '--color-card-gradient-from': '#f3f5f7',
            '--color-card-gradient-to': '#f8fafc',
            '--color-card-gradient-ai-from': '#f3f5f7',
            '--color-card-gradient-ai-to': '#f9fbfd',
        },
    },
    amber: {
        name: 'Amber',
        description: 'Premium amber aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0f0a00',
            '--color-bg-card': '#181000',
            '--color-bg-elevated': '#211601',
            '--color-text-main': '#fffaf3',
            '--color-text-muted': '#fcddaa',
            '--color-border': '#322002',
            '--color-border-hover': '#f59e0b',
            '--color-gold': '#f59e0b',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#ac6f08',
            '--color-gold-bg': 'rgba(245, 158, 11, 0.12)',
            '--color-card-gradient-from': '#181000',
            '--color-card-gradient-to': '#0f0a00',
            '--color-card-gradient-ai-from': '#181000',
            '--color-card-gradient-ai-to': '#0c0800',
        },
        lightColors: {
            '--color-bg-base': '#fffbeb',
            '--color-bg-card': '#faf6e6',
            '--color-bg-elevated': '#f2eedf',
            '--color-text-main': '#181001',
            '--color-text-muted': '#563704',
            '--color-border': '#e6e2d4',
            '--color-border-hover': '#f59e0b',
            '--color-gold': '#f59e0b',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#c47e09',
            '--color-gold-bg': 'rgba(245, 158, 11, 0.12)',
            '--color-card-gradient-from': '#faf6e6',
            '--color-card-gradient-to': '#fffbeb',
            '--color-card-gradient-ai-from': '#faf6e6',
            '--color-card-gradient-ai-to': '#fffcef',
        },
    },
    neon: {
        name: 'Neon',
        description: 'Premium neon aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0a000a',
            '--color-bg-card': '#130714',
            '--color-bg-elevated': '#1c0e1d',
            '--color-text-main': '#fefbff',
            '--color-text-muted': '#fae2fe',
            '--color-border': '#2d1a2e',
            '--color-border-hover': '#f0abfc',
            '--color-gold': '#f0abfc',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#a878b0',
            '--color-gold-bg': 'rgba(240, 171, 252, 0.12)',
            '--color-card-gradient-from': '#130714',
            '--color-card-gradient-to': '#0a000a',
            '--color-card-gradient-ai-from': '#130714',
            '--color-card-gradient-ai-to': '#080008',
        },
        lightColors: {
            '--color-bg-base': '#fdf4ff',
            '--color-bg-card': '#f8effa',
            '--color-bg-elevated': '#f0e8f2',
            '--color-text-main': '#181119',
            '--color-text-muted': '#543c58',
            '--color-border': '#e4dce6',
            '--color-border-hover': '#f0abfc',
            '--color-gold': '#f0abfc',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#c089ca',
            '--color-gold-bg': 'rgba(240, 171, 252, 0.12)',
            '--color-card-gradient-from': '#f8effa',
            '--color-card-gradient-to': '#fdf4ff',
            '--color-card-gradient-ai-from': '#f8effa',
            '--color-card-gradient-ai-to': '#fdf6ff',
        },
    },
    forest: {
        name: 'Forest',
        description: 'Premium forest aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#020a04',
            '--color-bg-card': '#031108',
            '--color-bg-elevated': '#05190b',
            '--color-text-main': '#f4fcf7',
            '--color-text-muted': '#b2ebc7',
            '--color-border': '#072612',
            '--color-border-hover': '#22c55e',
            '--color-gold': '#22c55e',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#188a42',
            '--color-gold-bg': 'rgba(34, 197, 94, 0.12)',
            '--color-card-gradient-from': '#031108',
            '--color-card-gradient-to': '#020a04',
            '--color-card-gradient-ai-from': '#031108',
            '--color-card-gradient-ai-to': '#020803',
        },
        lightColors: {
            '--color-bg-base': '#f0fdf4',
            '--color-bg-card': '#ebf8ef',
            '--color-bg-elevated': '#e4f0e8',
            '--color-text-main': '#031409',
            '--color-text-muted': '#0c4521',
            '--color-border': '#d8e4dc',
            '--color-border-hover': '#22c55e',
            '--color-gold': '#22c55e',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#1b9e4b',
            '--color-gold-bg': 'rgba(34, 197, 94, 0.12)',
            '--color-card-gradient-from': '#ebf8ef',
            '--color-card-gradient-to': '#f0fdf4',
            '--color-card-gradient-ai-from': '#ebf8ef',
            '--color-card-gradient-ai-to': '#f3fdf6',
        },
    },
    sunset2: {
        name: 'Sunset 2',
        description: 'Premium sunset 2 aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0f0206',
            '--color-bg-card': '#17030b',
            '--color-bg-elevated': '#1f050f',
            '--color-text-main': '#fdf4f8',
            '--color-text-muted': '#f2b3cf',
            '--color-border': '#2e0817',
            '--color-border-hover': '#db2777',
            '--color-gold': '#db2777',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#991b53',
            '--color-gold-bg': 'rgba(219, 39, 119, 0.12)',
            '--color-card-gradient-from': '#17030b',
            '--color-card-gradient-to': '#0f0206',
            '--color-card-gradient-ai-from': '#17030b',
            '--color-card-gradient-ai-to': '#0c0205',
        },
        lightColors: {
            '--color-bg-base': '#fdf2f8',
            '--color-bg-card': '#f8edf3',
            '--color-bg-elevated': '#f0e6ec',
            '--color-text-main': '#16040c',
            '--color-text-muted': '#4d0e2a',
            '--color-border': '#e4dadf',
            '--color-border-hover': '#db2777',
            '--color-gold': '#db2777',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#af1f5f',
            '--color-gold-bg': 'rgba(219, 39, 119, 0.12)',
            '--color-card-gradient-from': '#f8edf3',
            '--color-card-gradient-to': '#fdf2f8',
            '--color-card-gradient-ai-from': '#f8edf3',
            '--color-card-gradient-ai-to': '#fdf5f9',
        },
    },
    steel: {
        name: 'Steel',
        description: 'Premium steel aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#050a0f',
            '--color-bg-card': '#0b1016',
            '--color-bg-elevated': '#10161d',
            '--color-text-main': '#fafafb',
            '--color-text-muted': '#dadfe6',
            '--color-border': '#1a2128',
            '--color-border-hover': '#94a3b8',
            '--color-gold': '#94a3b8',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#687281',
            '--color-gold-bg': 'rgba(148, 163, 184, 0.12)',
            '--color-card-gradient-from': '#0b1016',
            '--color-card-gradient-to': '#050a0f',
            '--color-card-gradient-ai-from': '#0b1016',
            '--color-card-gradient-ai-to': '#04080c',
        },
        lightColors: {
            '--color-bg-base': '#f8fafc',
            '--color-bg-card': '#f3f5f7',
            '--color-bg-elevated': '#eceeef',
            '--color-text-main': '#0f1012',
            '--color-text-muted': '#343940',
            '--color-border': '#dfe1e3',
            '--color-border-hover': '#94a3b8',
            '--color-gold': '#94a3b8',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#768293',
            '--color-gold-bg': 'rgba(148, 163, 184, 0.12)',
            '--color-card-gradient-from': '#f3f5f7',
            '--color-card-gradient-to': '#f8fafc',
            '--color-card-gradient-ai-from': '#f3f5f7',
            '--color-card-gradient-ai-to': '#f9fbfd',
        },
    },
    lava: {
        name: 'Lava',
        description: 'Premium lava aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0f0500',
            '--color-bg-card': '#180803',
            '--color-bg-elevated': '#210a05',
            '--color-text-main': '#fef6f6',
            '--color-text-muted': '#f9bebe',
            '--color-border': '#310e0a',
            '--color-border-hover': '#ef4444',
            '--color-gold': '#ef4444',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#a73030',
            '--color-gold-bg': 'rgba(239, 68, 68, 0.12)',
            '--color-card-gradient-from': '#180803',
            '--color-card-gradient-to': '#0f0500',
            '--color-card-gradient-ai-from': '#180803',
            '--color-card-gradient-ai-to': '#0c0400',
        },
        lightColors: {
            '--color-bg-base': '#fef2f2',
            '--color-bg-card': '#f9eded',
            '--color-bg-elevated': '#f1e6e6',
            '--color-text-main': '#180707',
            '--color-text-muted': '#541818',
            '--color-border': '#e5dada',
            '--color-border-hover': '#ef4444',
            '--color-gold': '#ef4444',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#bf3636',
            '--color-gold-bg': 'rgba(239, 68, 68, 0.12)',
            '--color-card-gradient-from': '#f9eded',
            '--color-card-gradient-to': '#fef2f2',
            '--color-card-gradient-ai-from': '#f9eded',
            '--color-card-gradient-ai-to': '#fef5f5',
        },
    },
    cosmic: {
        name: 'Cosmic',
        description: 'Premium cosmic aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0a001a',
            '--color-bg-card': '#100323',
            '--color-bg-elevated': '#17072c',
            '--color-text-main': '#fbf7ff',
            '--color-text-muted': '#e1c4fc',
            '--color-border': '#220d3b',
            '--color-border-hover': '#a855f7',
            '--color-gold': '#a855f7',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#763bad',
            '--color-gold-bg': 'rgba(168, 85, 247, 0.12)',
            '--color-card-gradient-from': '#100323',
            '--color-card-gradient-to': '#0a001a',
            '--color-card-gradient-ai-from': '#100323',
            '--color-card-gradient-ai-to': '#080015',
        },
        lightColors: {
            '--color-bg-base': '#faf5ff',
            '--color-bg-card': '#f5f0fa',
            '--color-bg-elevated': '#eee9f2',
            '--color-text-main': '#110819',
            '--color-text-muted': '#3b1e56',
            '--color-border': '#e1dde6',
            '--color-border-hover': '#a855f7',
            '--color-gold': '#a855f7',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#8644c6',
            '--color-gold-bg': 'rgba(168, 85, 247, 0.12)',
            '--color-card-gradient-from': '#f5f0fa',
            '--color-card-gradient-to': '#faf5ff',
            '--color-card-gradient-ai-from': '#f5f0fa',
            '--color-card-gradient-ai-to': '#fbf7ff',
        },
    },
    mint: {
        name: 'Mint',
        description: 'Premium mint aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#000f08',
            '--color-bg-card': '#01160d',
            '--color-bg-elevated': '#011d12',
            '--color-text-main': '#f3fcf9',
            '--color-text-muted': '#abe7d3',
            '--color-border': '#02291a',
            '--color-border-hover': '#10b981',
            '--color-gold': '#10b981',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#0b825a',
            '--color-gold-bg': 'rgba(16, 185, 129, 0.12)',
            '--color-card-gradient-from': '#01160d',
            '--color-card-gradient-to': '#000f08',
            '--color-card-gradient-ai-from': '#01160d',
            '--color-card-gradient-ai-to': '#000c06',
        },
        lightColors: {
            '--color-bg-base': '#ecfdf5',
            '--color-bg-card': '#e7f8f0',
            '--color-bg-elevated': '#e0f0e9',
            '--color-text-main': '#02120d',
            '--color-text-muted': '#06412d',
            '--color-border': '#d4e4dd',
            '--color-border-hover': '#10b981',
            '--color-gold': '#10b981',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#0d9467',
            '--color-gold-bg': 'rgba(16, 185, 129, 0.12)',
            '--color-card-gradient-from': '#e7f8f0',
            '--color-card-gradient-to': '#ecfdf5',
            '--color-card-gradient-ai-from': '#e7f8f0',
            '--color-card-gradient-ai-to': '#f0fdf7',
        },
    },
    sand: {
        name: 'Sand',
        description: 'Premium sand aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0a0805',
            '--color-bg-card': '#120c05',
            '--color-bg-elevated': '#1b1105',
            '--color-text-main': '#fdf8f3',
            '--color-text-muted': '#f2cfa8',
            '--color-border': '#291905',
            '--color-border-hover': '#d97706',
            '--color-gold': '#d97706',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#985304',
            '--color-gold-bg': 'rgba(217, 119, 6, 0.12)',
            '--color-card-gradient-from': '#120c05',
            '--color-card-gradient-to': '#0a0805',
            '--color-card-gradient-ai-from': '#120c05',
            '--color-card-gradient-ai-to': '#080604',
        },
        lightColors: {
            '--color-bg-base': '#fffbeb',
            '--color-bg-card': '#faf6e6',
            '--color-bg-elevated': '#f2eedf',
            '--color-text-main': '#160c01',
            '--color-text-muted': '#4c2a02',
            '--color-border': '#e6e2d4',
            '--color-border-hover': '#d97706',
            '--color-gold': '#d97706',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#ae5f05',
            '--color-gold-bg': 'rgba(217, 119, 6, 0.12)',
            '--color-card-gradient-from': '#faf6e6',
            '--color-card-gradient-to': '#fffbeb',
            '--color-card-gradient-ai-from': '#faf6e6',
            '--color-card-gradient-ai-to': '#fffcef',
        },
    },
    arctic: {
        name: 'Arctic',
        description: 'Premium arctic aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#000a10',
            '--color-bg-card': '#001118',
            '--color-bg-elevated': '#001820',
            '--color-text-main': '#f3fbfd',
            '--color-text-muted': '#a8e5f0',
            '--color-border': '#01242d',
            '--color-border-hover': '#06b6d4',
            '--color-gold': '#06b6d4',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#047f94',
            '--color-gold-bg': 'rgba(6, 182, 212, 0.12)',
            '--color-card-gradient-from': '#001118',
            '--color-card-gradient-to': '#000a10',
            '--color-card-gradient-ai-from': '#001118',
            '--color-card-gradient-ai-to': '#00080d',
        },
        lightColors: {
            '--color-bg-base': '#ecfeff',
            '--color-bg-card': '#e7f9fa',
            '--color-bg-elevated': '#e0f1f2',
            '--color-text-main': '#011215',
            '--color-text-muted': '#02404a',
            '--color-border': '#d4e5e6',
            '--color-border-hover': '#06b6d4',
            '--color-gold': '#06b6d4',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#0592aa',
            '--color-gold-bg': 'rgba(6, 182, 212, 0.12)',
            '--color-card-gradient-from': '#e7f9fa',
            '--color-card-gradient-to': '#ecfeff',
            '--color-card-gradient-ai-from': '#e7f9fa',
            '--color-card-gradient-ai-to': '#f0feff',
        },
    },
    obsidian: {
        name: 'Obsidian',
        description: 'Premium obsidian aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#000000',
            '--color-bg-card': '#0a0a0a',
            '--color-bg-elevated': '#141414',
            '--color-text-main': '#ffffff',
            '--color-text-muted': '#ffffff',
            '--color-border': '#262626',
            '--color-border-hover': '#ffffff',
            '--color-gold': '#ffffff',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#b3b3b3',
            '--color-gold-bg': 'rgba(255, 255, 255, 0.12)',
            '--color-card-gradient-from': '#0a0a0a',
            '--color-card-gradient-to': '#000000',
            '--color-card-gradient-ai-from': '#0a0a0a',
            '--color-card-gradient-ai-to': '#000000',
        },
        lightColors: {
            '--color-bg-base': '#ffffff',
            '--color-bg-card': '#fafafa',
            '--color-bg-elevated': '#f2f2f2',
            '--color-text-main': '#191919',
            '--color-text-muted': '#595959',
            '--color-border': '#e6e6e6',
            '--color-border-hover': '#ffffff',
            '--color-gold': '#ffffff',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#cccccc',
            '--color-gold-bg': 'rgba(255, 255, 255, 0.12)',
            '--color-card-gradient-from': '#fafafa',
            '--color-card-gradient-to': '#ffffff',
            '--color-card-gradient-ai-from': '#fafafa',
            '--color-card-gradient-ai-to': '#ffffff',
        },
    },
    cherry: {
        name: 'Cherry',
        description: 'Premium cherry aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0f0508',
            '--color-bg-card': '#18070b',
            '--color-bg-elevated': '#210a0f',
            '--color-text-main': '#fef5f7',
            '--color-text-muted': '#fbbcc7',
            '--color-border': '#310e15',
            '--color-border-hover': '#f43f5e',
            '--color-gold': '#f43f5e',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#ab2c42',
            '--color-gold-bg': 'rgba(244, 63, 94, 0.12)',
            '--color-card-gradient-from': '#18070b',
            '--color-card-gradient-to': '#0f0508',
            '--color-card-gradient-ai-from': '#18070b',
            '--color-card-gradient-ai-to': '#0c0406',
        },
        lightColors: {
            '--color-bg-base': '#fff1f2',
            '--color-bg-card': '#faeced',
            '--color-bg-elevated': '#f2e5e6',
            '--color-text-main': '#180609',
            '--color-text-muted': '#551621',
            '--color-border': '#e6d9da',
            '--color-border-hover': '#f43f5e',
            '--color-gold': '#f43f5e',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#c3324b',
            '--color-gold-bg': 'rgba(244, 63, 94, 0.12)',
            '--color-card-gradient-from': '#faeced',
            '--color-card-gradient-to': '#fff1f2',
            '--color-card-gradient-ai-from': '#faeced',
            '--color-card-gradient-ai-to': '#fff4f5',
        },
    },
    toxic: {
        name: 'Toxic',
        description: 'Premium toxic aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#050a00',
            '--color-bg-card': '#0a1201',
            '--color-bg-elevated': '#0f1a02',
            '--color-text-main': '#f9fcf3',
            '--color-text-muted': '#d4edad',
            '--color-border': '#182703',
            '--color-border-hover': '#84cc16',
            '--color-gold': '#84cc16',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#5c8f0f',
            '--color-gold-bg': 'rgba(132, 204, 22, 0.12)',
            '--color-card-gradient-from': '#0a1201',
            '--color-card-gradient-to': '#050a00',
            '--color-card-gradient-ai-from': '#0a1201',
            '--color-card-gradient-ai-to': '#040800',
        },
        lightColors: {
            '--color-bg-base': '#f7fee7',
            '--color-bg-card': '#f2f9e2',
            '--color-bg-elevated': '#ebf1db',
            '--color-text-main': '#0d1402',
            '--color-text-muted': '#2e4708',
            '--color-border': '#dee5d0',
            '--color-border-hover': '#84cc16',
            '--color-gold': '#84cc16',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#6aa312',
            '--color-gold-bg': 'rgba(132, 204, 22, 0.12)',
            '--color-card-gradient-from': '#f2f9e2',
            '--color-card-gradient-to': '#f7fee7',
            '--color-card-gradient-ai-from': '#f2f9e2',
            '--color-card-gradient-ai-to': '#f9feec',
        },
    },
    candy: {
        name: 'Candy',
        description: 'Premium candy aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0a050f',
            '--color-bg-card': '#120818',
            '--color-bg-elevated': '#1b0a21',
            '--color-text-main': '#fdf6fe',
            '--color-text-muted': '#f2bef9',
            '--color-border': '#290f31',
            '--color-border-hover': '#d946ef',
            '--color-gold': '#d946ef',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#9831a7',
            '--color-gold-bg': 'rgba(217, 70, 239, 0.12)',
            '--color-card-gradient-from': '#120818',
            '--color-card-gradient-to': '#0a050f',
            '--color-card-gradient-ai-from': '#120818',
            '--color-card-gradient-ai-to': '#08040c',
        },
        lightColors: {
            '--color-bg-base': '#fdf4ff',
            '--color-bg-card': '#f8effa',
            '--color-bg-elevated': '#f0e8f2',
            '--color-text-main': '#160718',
            '--color-text-muted': '#4c1954',
            '--color-border': '#e4dce6',
            '--color-border-hover': '#d946ef',
            '--color-gold': '#d946ef',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#ae38bf',
            '--color-gold-bg': 'rgba(217, 70, 239, 0.12)',
            '--color-card-gradient-from': '#f8effa',
            '--color-card-gradient-to': '#fdf4ff',
            '--color-card-gradient-ai-from': '#f8effa',
            '--color-card-gradient-ai-to': '#fdf6ff',
        },
    },
    copper: {
        name: 'Copper',
        description: 'Premium copper aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0a0500',
            '--color-bg-card': '#110800',
            '--color-bg-elevated': '#180b01',
            '--color-text-main': '#fbf6f3',
            '--color-text-muted': '#e5c3a9',
            '--color-border': '#241101',
            '--color-border-hover': '#b45309',
            '--color-gold': '#b45309',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#7e3a06',
            '--color-gold-bg': 'rgba(180, 83, 9, 0.12)',
            '--color-card-gradient-from': '#110800',
            '--color-card-gradient-to': '#0a0500',
            '--color-card-gradient-ai-from': '#110800',
            '--color-card-gradient-ai-to': '#080400',
        },
        lightColors: {
            '--color-bg-base': '#fffbeb',
            '--color-bg-card': '#faf6e6',
            '--color-bg-elevated': '#f2eedf',
            '--color-text-main': '#120801',
            '--color-text-muted': '#3f1d03',
            '--color-border': '#e6e2d4',
            '--color-border-hover': '#b45309',
            '--color-gold': '#b45309',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#904207',
            '--color-gold-bg': 'rgba(180, 83, 9, 0.12)',
            '--color-card-gradient-from': '#faf6e6',
            '--color-card-gradient-to': '#fffbeb',
            '--color-card-gradient-ai-from': '#faf6e6',
            '--color-card-gradient-ai-to': '#fffcef',
        },
    },
    storm: {
        name: 'Storm',
        description: 'Premium storm aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#05051a',
            '--color-bg-card': '#090923',
            '--color-bg-elevated': '#0d0d2b',
            '--color-text-main': '#f7f7fe',
            '--color-text-muted': '#c8c9fa',
            '--color-border': '#13143a',
            '--color-border-hover': '#6366f1',
            '--color-gold': '#6366f1',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#4547a9',
            '--color-gold-bg': 'rgba(99, 102, 241, 0.12)',
            '--color-card-gradient-from': '#090923',
            '--color-card-gradient-to': '#05051a',
            '--color-card-gradient-ai-from': '#090923',
            '--color-card-gradient-ai-to': '#040415',
        },
        lightColors: {
            '--color-bg-base': '#eef2ff',
            '--color-bg-card': '#e9edfa',
            '--color-bg-elevated': '#e2e6f2',
            '--color-text-main': '#0a0a18',
            '--color-text-muted': '#232454',
            '--color-border': '#d6dae6',
            '--color-border-hover': '#6366f1',
            '--color-gold': '#6366f1',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#4f52c1',
            '--color-gold-bg': 'rgba(99, 102, 241, 0.12)',
            '--color-card-gradient-from': '#e9edfa',
            '--color-card-gradient-to': '#eef2ff',
            '--color-card-gradient-ai-from': '#e9edfa',
            '--color-card-gradient-ai-to': '#f1f5ff',
        },
    },
    ember: {
        name: 'Ember',
        description: 'Premium ember aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0a0200',
            '--color-bg-card': '#130500',
            '--color-bg-elevated': '#1c0901',
            '--color-text-main': '#fef7f3',
            '--color-text-muted': '#f8c5aa',
            '--color-border': '#2c0f02',
            '--color-border-hover': '#ea580c',
            '--color-gold': '#ea580c',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#a43e08',
            '--color-gold-bg': 'rgba(234, 88, 12, 0.12)',
            '--color-card-gradient-from': '#130500',
            '--color-card-gradient-to': '#0a0200',
            '--color-card-gradient-ai-from': '#130500',
            '--color-card-gradient-ai-to': '#080200',
        },
        lightColors: {
            '--color-bg-base': '#fff7ed',
            '--color-bg-card': '#faf2e8',
            '--color-bg-elevated': '#f2ebe1',
            '--color-text-main': '#170901',
            '--color-text-muted': '#521f04',
            '--color-border': '#e6ded5',
            '--color-border-hover': '#ea580c',
            '--color-gold': '#ea580c',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#bb460a',
            '--color-gold-bg': 'rgba(234, 88, 12, 0.12)',
            '--color-card-gradient-from': '#faf2e8',
            '--color-card-gradient-to': '#fff7ed',
            '--color-card-gradient-ai-from': '#faf2e8',
            '--color-card-gradient-ai-to': '#fff9f1',
        },
    },
    royal: {
        name: 'Royal',
        description: 'Premium royal aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#05000f',
            '--color-bg-card': '#0a0418',
            '--color-bg-elevated': '#100721',
            '--color-text-main': '#f9f7ff',
            '--color-text-muted': '#d6c6fc',
            '--color-border': '#190e32',
            '--color-border-hover': '#8b5cf6',
            '--color-gold': '#8b5cf6',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#6140ac',
            '--color-gold-bg': 'rgba(139, 92, 246, 0.12)',
            '--color-card-gradient-from': '#0a0418',
            '--color-card-gradient-to': '#05000f',
            '--color-card-gradient-ai-from': '#0a0418',
            '--color-card-gradient-ai-to': '#04000c',
        },
        lightColors: {
            '--color-bg-base': '#f5f3ff',
            '--color-bg-card': '#f0eefa',
            '--color-bg-elevated': '#e9e7f2',
            '--color-text-main': '#0e0919',
            '--color-text-muted': '#312056',
            '--color-border': '#dddbe6',
            '--color-border-hover': '#8b5cf6',
            '--color-gold': '#8b5cf6',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#6f4ac5',
            '--color-gold-bg': 'rgba(139, 92, 246, 0.12)',
            '--color-card-gradient-from': '#f0eefa',
            '--color-card-gradient-to': '#f5f3ff',
            '--color-card-gradient-ai-from': '#f0eefa',
            '--color-card-gradient-ai-to': '#f7f5ff',
        },
    },
    rose: {
        name: 'Rose',
        description: 'Premium rose aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0a0005',
            '--color-bg-card': '#130108',
            '--color-bg-elevated': '#1b020a',
            '--color-text-main': '#fef4f6',
            '--color-text-muted': '#f5b0bf',
            '--color-border': '#2a040f',
            '--color-border-hover': '#e11d48',
            '--color-gold': '#e11d48',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#9e1432',
            '--color-gold-bg': 'rgba(225, 29, 72, 0.12)',
            '--color-card-gradient-from': '#130108',
            '--color-card-gradient-to': '#0a0005',
            '--color-card-gradient-ai-from': '#130108',
            '--color-card-gradient-ai-to': '#080004',
        },
        lightColors: {
            '--color-bg-base': '#fff1f2',
            '--color-bg-card': '#faeced',
            '--color-bg-elevated': '#f2e5e6',
            '--color-text-main': '#160307',
            '--color-text-muted': '#4f0a19',
            '--color-border': '#e6d9da',
            '--color-border-hover': '#e11d48',
            '--color-gold': '#e11d48',
            '--color-gold-fg': '#ffffff',
            '--color-gold-dark': '#b4173a',
            '--color-gold-bg': 'rgba(225, 29, 72, 0.12)',
            '--color-card-gradient-from': '#faeced',
            '--color-card-gradient-to': '#fff1f2',
            '--color-card-gradient-ai-from': '#faeced',
            '--color-card-gradient-ai-to': '#fff4f5',
        },
    },
    sunset: {
        name: 'Sunset',
        description: 'Premium sunset aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0f0500',
            '--color-bg-card': '#180901',
            '--color-bg-elevated': '#220e02',
            '--color-text-main': '#fff8f3',
            '--color-text-muted': '#fdcead',
            '--color-border': '#321603',
            '--color-border-hover': '#f97316',
            '--color-gold': '#f97316',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#ae510f',
            '--color-gold-bg': 'rgba(249, 115, 22, 0.12)',
            '--color-card-gradient-from': '#180901',
            '--color-card-gradient-to': '#0f0500',
            '--color-card-gradient-ai-from': '#180901',
            '--color-card-gradient-ai-to': '#0c0400',
        },
        lightColors: {
            '--color-bg-base': '#fff7ed',
            '--color-bg-card': '#faf2e8',
            '--color-bg-elevated': '#f2ebe1',
            '--color-text-main': '#190b02',
            '--color-text-muted': '#572808',
            '--color-border': '#e6ded5',
            '--color-border-hover': '#f97316',
            '--color-gold': '#f97316',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#c75c12',
            '--color-gold-bg': 'rgba(249, 115, 22, 0.12)',
            '--color-card-gradient-from': '#faf2e8',
            '--color-card-gradient-to': '#fff7ed',
            '--color-card-gradient-ai-from': '#faf2e8',
            '--color-card-gradient-ai-to': '#fff9f1',
        },
    },
    ocean: {
        name: 'Ocean',
        description: 'Premium ocean aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#000a0f',
            '--color-bg-card': '#011018',
            '--color-bg-elevated': '#011620',
            '--color-text-main': '#f3fbfe',
            '--color-text-muted': '#abe0f7',
            '--color-border': '#022130',
            '--color-border-hover': '#0ea5e9',
            '--color-gold': '#0ea5e9',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#0a73a3',
            '--color-gold-bg': 'rgba(14, 165, 233, 0.12)',
            '--color-card-gradient-from': '#011018',
            '--color-card-gradient-to': '#000a0f',
            '--color-card-gradient-ai-from': '#011018',
            '--color-card-gradient-ai-to': '#00080c',
        },
        lightColors: {
            '--color-bg-base': '#f0f9ff',
            '--color-bg-card': '#ebf4fa',
            '--color-bg-elevated': '#e4edf2',
            '--color-text-main': '#011017',
            '--color-text-muted': '#053a52',
            '--color-border': '#d8e0e6',
            '--color-border-hover': '#0ea5e9',
            '--color-gold': '#0ea5e9',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#0b84ba',
            '--color-gold-bg': 'rgba(14, 165, 233, 0.12)',
            '--color-card-gradient-from': '#ebf4fa',
            '--color-card-gradient-to': '#f0f9ff',
            '--color-card-gradient-ai-from': '#ebf4fa',
            '--color-card-gradient-ai-to': '#f3faff',
        },
    },
    darkSouls: {
        name: 'Dark Souls',
        description: 'Premium dark souls aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#000000',
            '--color-bg-card': '#090909',
            '--color-bg-elevated': '#121212',
            '--color-text-main': '#fefefe',
            '--color-text-muted': '#f6f6f6',
            '--color-border': '#222222',
            '--color-border-hover': '#e5e5e5',
            '--color-gold': '#e5e5e5',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#a0a0a0',
            '--color-gold-bg': 'rgba(229, 229, 229, 0.12)',
            '--color-card-gradient-from': '#090909',
            '--color-card-gradient-to': '#000000',
            '--color-card-gradient-ai-from': '#090909',
            '--color-card-gradient-ai-to': '#000000',
        },
        lightColors: {
            '--color-bg-base': '#f5f5f5',
            '--color-bg-card': '#f0f0f0',
            '--color-bg-elevated': '#e9e9e9',
            '--color-text-main': '#171717',
            '--color-text-muted': '#505050',
            '--color-border': '#dddddd',
            '--color-border-hover': '#e5e5e5',
            '--color-gold': '#e5e5e5',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#b7b7b7',
            '--color-gold-bg': 'rgba(229, 229, 229, 0.12)',
            '--color-card-gradient-from': '#f0f0f0',
            '--color-card-gradient-to': '#f5f5f5',
            '--color-card-gradient-ai-from': '#f0f0f0',
            '--color-card-gradient-ai-to': '#f7f7f7',
        },
    },
    pearl: {
        name: 'Pearl',
        description: 'Premium pearl aesthetic',
        isDark: true,
        lightMode: true,
        colors: {
            '--color-bg-base': '#0f0f12',
            '--color-bg-card': '#18181b',
            '--color-bg-elevated': '#222225',
            '--color-text-main': '#ffffff',
            '--color-text-muted': '#fdfdfe',
            '--color-border': '#323235',
            '--color-border-hover': '#f8fafc',
            '--color-gold': '#f8fafc',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#aeafb0',
            '--color-gold-bg': 'rgba(248, 250, 252, 0.12)',
            '--color-card-gradient-from': '#18181b',
            '--color-card-gradient-to': '#0f0f12',
            '--color-card-gradient-ai-from': '#18181b',
            '--color-card-gradient-ai-to': '#0c0c0e',
        },
        lightColors: {
            '--color-bg-base': '#ffffff',
            '--color-bg-card': '#fafafa',
            '--color-bg-elevated': '#f2f2f2',
            '--color-text-main': '#191919',
            '--color-text-muted': '#575858',
            '--color-border': '#e6e6e6',
            '--color-border-hover': '#f8fafc',
            '--color-gold': '#f8fafc',
            '--color-gold-fg': '#000000',
            '--color-gold-dark': '#c6c8ca',
            '--color-gold-bg': 'rgba(248, 250, 252, 0.12)',
            '--color-card-gradient-from': '#fafafa',
            '--color-card-gradient-to': '#ffffff',
            '--color-card-gradient-ai-from': '#fafafa',
            '--color-card-gradient-ai-to': '#ffffff',
        },
    },
};

export const themeNames = Object.keys(themes);
export const defaultTheme = 'golden';
