<?php

return [
    'currency' => env('APP_CURRENCY', 'MAD'),
    'balance' => [
        'base' => env('BASE_BALANCE', 12500.00),
    ],
    'card' => [
        'last4' => env('DEFAULT_CARD_LAST4', '9984'),
        'expiry' => env('DEFAULT_CARD_EXPIRY', '12/28'),
        'limit' => env('DEFAULT_CARD_LIMIT', 50000),
        'gradient' => env('DEFAULT_CARD_GRADIENT', 'linear-gradient(135deg, #1a1a1a 0%, #0a0a0a 100%)'),
        'texture_url' => env('DEFAULT_CARD_TEXTURE', 'url("https://www.transparenttextures.com/patterns/carbon-fibre.png")'),
        'chip_gradient' => 'from-yellow-200 via-yellow-400 to-yellow-600',
    ],
    'rib' => [
        'full' => env('RIB_FULL', '181 810 0000000000000000 84'),
        'bank_code' => env('RIB_BANK_CODE', '181'),
        'branch_code' => env('RIB_BRANCH_CODE', '810'),
        'account_number' => env('RIB_ACCOUNT_NUMBER', '0000000000000000'),
        'rib_key' => env('RIB_KEY', '84'),
        'min_length' => 16,
    ],
    'account' => [
        'type' => env('ACCOUNT_TYPE', 'Standard Checking'),
        'branch' => env('ACCOUNT_BRANCH', 'Casablanca Main'),
    ],
    'limits' => [
        'max_transfer' => env('MAX_TRANSFER', 500000),
        'max_deposit' => env('MAX_DEPOSIT', 500000),
        'max_withdrawal' => env('MAX_WITHDRAWAL', 500000),
        'pagination' => env('PAGINATION_PER_PAGE', 20),
        'contacts_recent' => 5,
        'contacts_search' => 20,
        'notifications_recent' => 5,
        'subscription_history' => 15,
        'receive_recent' => 10,
        'admin_recent_users' => 5,
        'admin_recent_loans' => 5,
        'admin_search_limit' => 10,
        'report_user_growth_days' => 30,
        'report_revenue_months' => 12,
        'report_top_users' => 10,
        'active_users_days' => 7,
        'new_accounts_days' => 7,
        'recent_transactions' => 8,
        'recent_transfers' => 10,
        'beneficiaries' => 8,
        'recent_sends' => 10,
        'decimal_precision' => 2,
    ],
    'date_formats' => [
        'default' => 'Y-m-d',
        'datetime' => 'Y-m-d H:i',
        'month_year' => 'M Y',
        'year_month' => 'Y-m',
        'display_short' => 'd M Y',
        'display_long' => 'd M Y, H:i',
    ],
    'colors' => [
        'deposit' => '#D4AF37',
        'withdrawal' => '#EF4444',
        'credit' => '#10B981',
        'debit' => '#EF4444',
        'transfer' => ['#D4AF37', '#3B82F6', '#10B981', '#8B5CF6', '#F59E0B', '#EC4899'],
        'default_avatar' => '#64748B',
        'default_logo' => '#D4AF37',
        'chart_palette' => ['#D4AF37', '#10B981', '#6366F1', '#F59E0B', '#EC4899', '#8B5CF6', '#06B6D4', '#EF4444', '#3B82F6', '#84CC16'],
        'status' => [
            'success' => '#10B981',
            'warning' => '#F59E0B',
            'error' => '#EF4444',
            'info' => '#3B82F6',
        ],
    ],
    'admin' => [
        'name' => env('APP_NAME', 'OSCORP') . ' Admin Console',
        'date_format_short' => 'd M Y',
        'date_format_long' => 'd M Y, H:i',
        'stats_colors' => [
            'primary' => 'var(--color-gold)',
            'blue' => '#3b82f6',
            'green' => '#10b981',
            'amber' => '#f59e0b',
            'red' => '#ef4444',
        ],
        'status_colors' => [
            'pending' => ['bg' => 'rgba(245,158,11,0.15)', 'text' => '#f59e0b'],
            'approved' => ['bg' => 'rgba(16,185,129,0.15)', 'text' => '#10b981'],
            'active' => ['bg' => 'rgba(59,130,246,0.15)', 'text' => '#3b82f6'],
            'rejected' => ['bg' => 'rgba(239,68,68,0.15)', 'text' => '#ef4444'],
            'completed' => ['bg' => 'rgba(16,185,129,0.15)', 'text' => '#10b981'],
            'failed' => ['bg' => 'rgba(239,68,68,0.15)', 'text' => '#ef4444'],
            'paid' => ['bg' => 'rgba(16,185,129,0.15)', 'text' => '#10b981'],
            'expired' => ['bg' => 'rgba(239,68,68,0.15)', 'text' => '#ef4444'],
        ],
    ],
];
